---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: message-consumer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: message-consumer
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - external:
      metric:
        name: rabbitmq_queue_messages
      target:
        type: Value
        value: "10"
    type: External
