{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "dotnet-core-webapi.fullname" . }}-hpa
  namespace: {{ include "dotnet-core-webapi.namespace" . }}
  labels: {{ include "dotnet-core-webapi.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    {{ if eq .Values.strategy "standard" }}
    apiVersion: apps/v1
    kind: Deployment
    {{ else }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    {{ end }}
    name: {{ .Release.Name }}-deployment
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hpa.stabilizationWindowSeconds }}    # Scale down delay (in seconds)
      policies:
        - type: {{ .Values.hpa.scaleDownType }}
          value: {{ .Values.hpa.scaleDownValue }}                      # Scale down by 1 pod at a time
          periodSeconds: {{ .Values.hpa.scaleDownPeriodSeconds }}             # Allow scale down every 60 seconds
    scaleUp:
      policies:
        - type: {{ .Values.hpa.scaleUpType }}
          value: {{ .Values.hpa.scaleUpValue }}                    # Scale up by doubling pods if needed
          periodSeconds: {{ .Values.hpa.scaleUpPeriodSeconds }}             # Allow scaling up every 15 seconds
{{- end }}

