apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-2048
  namespace: game-2048
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-2048
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
