{{- $nautobots := (include "nautobot.nautobots" .) | mustFromJson -}}
{{- range $nautobotName, $nautobot := $nautobots -}}
{{- if (and $nautobot.enabled $nautobot.autoscaling.enabled) }}
---
apiVersion: {{ include "common.capabilities.hpa.apiVersion" $ }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.names.fullname" $ }}-{{ $nautobotName }}
  labels:
    app.kubernetes.io/component: nautobot-{{ $nautobotName }}
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "common.names.fullname" $ }}-{{ $nautobotName }}
  minReplicas: {{ $nautobot.autoscaling.minReplicas | int }}
  maxReplicas: {{ $nautobot.autoscaling.maxReplicas | int }}
  metrics:
    {{- toYaml $nautobot.autoscaling.metrics | nindent 4 }}
  behavior:
    {{- toYaml $nautobot.autoscaling.behavior | nindent 4 }}
{{- end }}
{{- end }}
