{{- if .Values.acapy.autoscaling.enabled }}
{{- $acapyFullName := include "acapy.fullname" . -}}
apiVersion: {{ include "common.capabilities.hpa.apiVersion" ( dict "context" $ ) }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $acapyFullName }}
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $acapyFullName }}
  minReplicas: {{ .Values.acapy.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.acapy.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.acapy.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.acapy.autoscaling.targetCPUUtilizationPercentage }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.acapy.autoscaling.targetCPUUtilizationPercentage }}
        {{- end }}
    {{- end }}
    {{- if .Values.acapy.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.acapy.autoscaling.targetMemoryUtilizationPercentage }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.acapy.autoscaling.targetMemoryUtilizationPercentage }}
        {{- end }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.acapy.autoscaling.stabilizationWindowSeconds }}
{{- end }}
