---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ifconfig
  namespace: ifconfig
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ifconfig
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
