kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  labels:
    app: noobaa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: noobaa-endpoint
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
