apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kwetter-user-service-autoscaler
  namespace: kwetter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kwetter-user-service
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
