{{- if .Values.worker.autoscale.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-worker" .Release.Name | quote }}
  labels:
    {{- include "laravelapp.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-worker" .Release.Name | quote }}
  minReplicas: {{ .Values.worker.autoscale.minReplicas }}
  maxReplicas: {{ .Values.worker.autoscale.maxReplicas }}
  {{- if .Values.worker.autoscale.CPULimit }}
  metrics: 
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization 
        averageUtilization: {{ .Values.worker.autoscale.CPULimit }}
  {{ end }}
  {{- if .Values.worker.autoscale.MemoryLimit }}
  - type: Resource
    resource:
      name: memory 
      target:
        type: AverageValue 
        averageValue: {{ .Values.worker.autoscale.MemoryLimit }}
  {{ end }}
{{ end }}
