apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.consulconfig.diskName }}-{{ .Release.Namespace }}
  namespace: {{ .Values.global.namespace }}
  labels:
    component: {{ .Values.volumes.consulconfig.diskName }}
spec:
  capacity:
    storage: {{ .Values.volumes.size }}
  accessModes:
    - {{ .Values.volumes.accessMode }}
  hostPath:
    path: {{ .Values.volumes.consulconfig.path }}-{{ .Release.Namespace }}
  persistentVolumeReclaimPolicy: Delete
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.volumes.consulconfig.claimName }}
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - {{ .Values.volumes.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volumes.size }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.consuldata.diskName }}-{{ .Release.Namespace }}
  namespace: {{ .Values.global.namespace }}
  labels:
    component: {{ .Values.volumes.consuldata.diskName }}
spec:
  capacity:
    storage: {{ .Values.volumes.size }}
  accessModes:
    - {{ .Values.volumes.accessMode }}
  hostPath:
    path: {{ .Values.volumes.consuldata.path }}-{{ .Release.Namespace }}
  persistentVolumeReclaimPolicy: Delete
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.volumes.consuldata.claimName }}
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - {{ .Values.volumes.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volumes.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.consul.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    io.kompose.service: {{ .Values.consul.name }}
  annotations:
spec:
  ports:
    - port: {{ .Values.consul.ports.server }}
      name: server
    - port: {{ .Values.consul.ports.cli_rpc }}
      name: cli-rpc
    - port: {{ .Values.consul.ports.http }}
      name: http
    - port: {{ .Values.consul.ports.https }}
      name: https
    - port: {{ .Values.consul.ports.dns }}
      name: dns
  selector:
    io.kompose.service: {{ .Values.consul.name }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    io.kompose.service: {{ .Values.consul.name }}
  name: {{ .Values.consul.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ .Values.consul.name }}
  minReplicas: {{ .Values.global.hpa.min }}
  maxReplicas: {{ .Values.global.hpa.max }}
  metrics:
  - type: Resource
    resource:
      name: {{ .Values.global.hpa.metric }}
      targetAverageUtilization: {{ .Values.global.hpa.utilization }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .Values.consul.name }}
  name: {{ .Values.consul.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
spec:
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.consul.name }}
    spec:
      containers:
      - image: {{ .Values.coreConsulImage }}
        name: {{ .Values.consul.name }}
        ports:
        - containerPort: {{ .Values.consul.ports.server }}
        - containerPort: {{ .Values.consul.ports.cli_rpc }}
        - containerPort: {{ .Values.consul.ports.http }}
        - containerPort: {{ .Values.consul.ports.https }}
        - containerPort: {{ .Values.consul.ports.dns }}
        resources: {}
        volumeMounts:
        - mountPath: {{ .Values.volumes.consulconfig.mountPath }}
          name: {{ .Values.volumes.consulconfig.name }}
        - mountPath: {{ .Values.volumes.consuldata.mountPath }}
          name: {{ .Values.volumes.consuldata.name }}
      restartPolicy: Always
      volumes:
      - name: {{ .Values.volumes.consulconfig.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volumes.consulconfig.claimName }}
      - name: {{ .Values.volumes.consuldata.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volumes.consuldata.claimName }}
