apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-browserless
  labels:
    app: rs-browserless
spec:
  selector:
    matchLabels:
      app: rs-browserless
  template:
    metadata:
      labels:
        app: rs-browserless
    spec:
      containers:
        - name: rs-browserless
          image: browserless/chrome:1.61.0-puppeteer-21.4.1
          ports:
            - containerPort: 3000
          env:
            - name: MAX_CONCURRENT_SESSIONS
              value: "3"
            - name: MAX_QUEUE_LENGTH
              value: "10"
            - name: DEFAULT_BLOCK_ADS
              value: "true"
            - name: DEFAULT_LAUNCH_ARGS
              value: '["--disable-web-security"]'
            - name: WORKSPACE_DELETE_EXPIRED
              value: "true"
            - name: WORKSPACE_EXPIRE_DAYS
              value: "1"
            - name: EXIT_ON_HEALTH_FAILURE
              value: "true"
            - name: PREBOOT_CHROME
              value: "true"
            - name: KEEP_ALIVE
              value: "true"
            - name: FUNCTION_ENABLE_INCOGNITO_MODE
              value: "true"
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: rs-api-env
                  key: BROWSERLESS_TOKEN
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
            limits:
              cpu: 1.2
              memory: 700Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rs-browserless
spec:
  type: ClusterIP
  selector:
    app: rs-browserless
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rs-browserless
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rs-browserless
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageValue: 400m
