apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: whereis-store-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: whereis-store-app-deployment
  minReplicas: 1
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80