apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-server-1
  labels:
    app: app-server-1
    example: hpa-1
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-server-1
  targetCPUUtilizationPercentage: 90
