apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample
  labels:
    app.kubernetes.io/name: sample
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60