apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-ecommerce
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ecommerce-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70 # com 70 % de CPU ele cria outro pod, também é possivel criar um para criar novos workers no cluster