apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-routr-apiserver-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-routr-apiserver
  minReplicas: {{ .Values.apiserver.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.apiserver.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.apiserver.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.apiserver.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.apiserver.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.apiserver.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
