apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: k8app-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8app-backend
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60