apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: open-ocr-httpd
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: open-ocr-httpd
 minReplicas: 1
 maxReplicas: 500
 targetCPUUtilizationPercentage: 2
