apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fdic-api-hpa
  namespace: remkohdev-ns
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: fdic-api-deployment
  targetCPUUtilizationPercentage: 80