---
apiVersion: v1
kind: Service
metadata:
  name: search-{{ include "hotelres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hotelres.labels" . | nindent 4 }}
    app-name: search
spec:
  type: {{ include "hotelres.get" (list .Values "search" "service.type") }}
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    {{- include "hotelres.selectorLabels" . | nindent 4 }}
    app-name: search

{{- if (include "hotelres.get" (list .Values "search" "autoscaling.enabled" "json") | mustFromJson) }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: search-{{ include "hotelres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hotelres.labels" . | nindent 4 }}
    app-name: search
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-{{ include "hotelres.fullname" . }}
  minReplicas: {{ include "hotelres.get" (list .Values "search" "autoscaling.minReplicas") }}
  maxReplicas: {{ include "hotelres.get" (list .Values "search" "autoscaling.maxReplicas") }}
  metrics:
    {{- if (include "hotelres.get" (list .Values "search" "autoscaling.targetCPUUtilizationPercentage" "json") | mustFromJson) }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ include "hotelres.get" (list .Values "search" "autoscaling.targetCPUUtilizationPercentage") }}
    {{- end }}
    {{- if (include "hotelres.get" (list .Values "search" "autoscaling.targetMemoryUtilizationPercentage" "json") | mustFromJson) }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ include "hotelres.get" (list .Values "search" "autoscaling.targetMemoryUtilizationPercentage") }}
    {{- end }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-{{ include "hotelres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hotelres.labels" . | nindent 4 }}
    app-name: search
spec:
  {{- if not (include "hotelres.get" (list .Values "search" "autoscaling.enabled" "json") | mustFromJson) }}
  replicas: {{ include "hotelres.get" (list .Values "search" "replicaCount") }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hotelres.selectorLabels" . | nindent 6 }}
      app-name: search
  template:
    metadata:
      annotations:
        cri-resource-manager.intel.com/affinity: |
          search:
            - scope:
                key: pod/namespace
                operator: In
                values:
                  - {{ .Release.Namespace }}
              match:
                operator: AlwaysTrue
              weight: 111
        cri-resource-manager.intel.com/anti-affinity: |
          search:
            - scope:
                key: pod/namespace
                operator: NotIn
                values:
                  - {{ .Release.Namespace }}
              match:
                operator: AlwaysTrue
              weight: 111
      {{- with (include "hotelres.get" (list .Values "search" "podAnnotations" "json") | mustFromJson) }}
        {{- toYaml . | nindent 8}}
      {{- end }}
      labels:
        {{- include "hotelres.selectorLabels" . | nindent 8 }}
        app-name: search
    spec:
      {{- if .Values.evenly_distributed }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "hotelres.selectorLabels" . | nindent 14 }}
              app-name: search
      {{- end }}
      {{- with (include "hotelres.get" (list .Values "search" "imagePullSecrets" "json") | mustFromJson) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "hotelres.serviceAccountName" . }}
      {{- end }}
      {{- with (include "hotelres.get" (list .Values "search" "podSecurityContext" "json") | mustFromJson) }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: search
          {{- with (include "hotelres.get" (list .Values "search" "securityContext" "json") | mustFromJson) }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "hotelres.get" (list .Values "search" "image.repository") }}:{{ include "hotelres.get" (list .Values "search" "image.tag") | default .Chart.AppVersion }}
          imagePullPolicy: {{ include "hotelres.get" (list .Values "search" "image.pullPolicy") }}
          command:
            - search
          ports:
            - containerPort: 8082
          env:
            - name: TLS
              value: {{ include "hotelres.get" (list .Values "search" "features.tls") | quote }}
            - name: JAEGER_SAMPLE_RATIO
              value: {{ include "hotelres.get" (list .Values "search" "features.jaegerSampleRatio") | quote }}
            - name: GC
              value: {{ include "hotelres.get" (list .Values "search" "features.gcPercent") | quote }}
          {{- with (include "hotelres.get" (list .Values "search" "environments" "json") | mustFromJson) }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with (include "hotelres.get" (list .Values "search" "resources" "json") | mustFromJson) }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /go/src/github.com/harlow/go-micro-services/config.json
              subPath: config.json
              name: config-json
          {{- if include "hotelres.needhugepage" (list .Values "search") }}
            - mountPath: /hugepages
              name: hugepage
          {{- end }}
      volumes:
        - name: config-json
          configMap:
            name: configmap-{{ include "hotelres.fullname" . }}
            items:
            - key: config.json
              path: config.json
      {{- if include "hotelres.needhugepage" (list .Values "search") }}
        - name: hugepage
          emptyDir:
            medium: HugePages
      {{- end }}
      {{- with (include "hotelres.get" (list .Values "search" "nodeSelector" "json") | mustFromJson) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (include "hotelres.get" (list .Values "search" "affinity" "json") | mustFromJson) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (include "hotelres.get" (list .Values "search" "tolerations" "json") | mustFromJson) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
