---
apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: rider-auto-rest-autoscaler
spec:
  scaleRef:
    kind: ReplicationController
    name: rider-auto-rest
    apiVersion: v1
    subresource: scale
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization:
    targetPercentage: 50