apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-depl
  namespace: foo
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: hello-world
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaler
  namespace: foo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-depl
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80