# {{ if eq .Cluster.ConfigItems.kubelet_summary_metrics_enabled "true" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kubelet-summary-metrics
  namespace: kube-system
  labels:
    application: kubernetes
    component: kubelet-summary-metrics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubelet-summary-metrics
  minReplicas: 2
  maxReplicas: {{.Cluster.ConfigItems.kubelet_summary_metrics_hpa_max_replicas}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{.Cluster.ConfigItems.kubelet_summary_metrics_hpa_cpu_target}}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{.Cluster.ConfigItems.kubelet_summary_metrics_hpa_memory_target}}
# {{ end }}
