apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appName }}-autoscale
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  minReplicas: {{ .Values.global.conf_agent_server.minReplicas }}
  maxReplicas: {{ .Values.global.conf_agent_server.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}-deployment
  targetCPUUtilizationPercentage: {{ .Values.global.conf_agent_server.hpaTargetCPUUtilizationPercentage  | default "65"}}
