apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "k8app-chart.fullname" . }}-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "k8app-chart.fullname" . }}-frontend
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60