apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-diffusion-endpt
  labels:
    name: stable-diffusion-endpt
spec:
  replicas: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 1 #change it to 0 requires another node with GPU, increasing time and costs, but it's good for reliability
  selector:
    matchLabels:
      name: stable-diffusion-endpt
  template:
    metadata:
      labels:
        name: stable-diffusion-endpt
        version: stable
      annotations:
        instrumentation.opentelemetry.io/inject-python: "genai-instrumentation"
    spec:
      restartPolicy: Always
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-l4"
        cloud.google.com/compute-class: "Accelerator"
      containers:
      - image: stable-diffusion-endpt
        name: stable-diffusion-endpt
        imagePullPolicy: Always
        ports:
        - name: http-front
          containerPort: 8080
          protocol: TCP
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: http-front
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        # livenessProbe:
        #   tcpSocket:
        #     port: http-front
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        env:
        - name: ENV
          value: dev
        - name: MODEL_TYPE
          value: dreamlike-art/dreamlike-photoreal-2.0
        resources:
          requests:
            cpu: 500m # 500m
            memory: 4Gi # 3Gi
            nvidia.com/gpu: 1
          limits:
            memory: 4Gi # 3Gi
            nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: stable-diffusion-endpt
  name: stable-diffusion-endpt
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    name: stable-diffusion-endpt
  sessionAffinity: None
  type: ClusterIP
# ---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: stable-diffusion-endpt
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: stable-diffusion-endpt
#   minReplicas: 5
#   maxReplicas: 30
#   targetCPUUtilizationPercentage: 50
