apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: simple-rest
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: simple-rest
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 10
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 10    